Repository easyops-cn/next-basics, pull requests merged in 2021-06, with the labels that each got.

#388 chore(): add test id
  bricks/basic-bricks/src/popover-container/PopoverContainer.tsx
  bricks/basic-bricks/stories/chapters/popover-container.ts
  bricks/forms/stories/chapters/general-auto-complete.ts
  bricks/forms/stories/chapters/general-input.ts
  bricks/forms/stories/chapters/general-radio.ts
  bricks/presentational-bricks/src/general-tooltip/GeneralTooltip.tsx
  bricks/presentational-bricks/stories/chapters/brick-link.ts
  bricks/presentational-bricks/stories/chapters/brick-table.ts
  bricks/presentational-bricks/stories/chapters/brick-tree.ts
  bricks/presentational-bricks/stories/chapters/general-tooltip.ts
Labels: enhancement

#394 chore(menu-bar): add testid
  bricks/basic-bricks/src/menu-bar/AppSubMenu/AppSubMenu.tsx
  bricks/basic-bricks/src/menu-bar/MenuBar/MenuBar.tsx
Labels: enhancement

#398 feat(): general-drawer add loading props
  bricks/basic-bricks/src/general-drawer/GeneralDrawer.spec.tsx
  bricks/basic-bricks/src/general-drawer/GeneralDrawer.tsx
  bricks/basic-bricks/src/general-drawer/index.shadow.less
  bricks/basic-bricks/src/general-drawer/index.tsx
Labels: enhancement, eve: release after merged

#417 feat(general-timer): timer suppert stop and reStart
  bricks/basic-bricks/src/general-timer/index.tsx
Labels: eve: release after merged

#418 chore(): update doc
  bricks/basic-bricks/src/general-timer/index.tsx
Labels: eve: release after merged

#430 feat(): add general card editor
  bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.module.css
  bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.spec.tsx
  bricks/shared-editors/src/editor-bricks/general-card/general-card.editor.tsx
  bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.tsx
  bricks/shared-editors/src/editor-bricks/general-code/general-code.editor.tsx
  bricks/shared-editors/src/editor-bricks/general-menu/general-menu.editor.tsx
  bricks/shared-editors/src/editor-bricks/index.ts
Labels: eve: release after merged

#433 fix(easy-view--editor): set min-height to 100%
  bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.module.css
  bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.spec.tsx
  bricks/basic-bricks/src/editor-bricks/easy-view/easy-view.editor.tsx
Labels: eve: release after merged

#434 fix(): remove unused code
  bricks/shared-editors/src/editor-bricks/general-chart/general-chart.editor.tsx
Labels: eve: release after merged

#455 feat(): fetch snippets by flags
  bricks/next-builder/src/data-providers/GetBrickLibrary.spec.ts
  bricks/next-builder/src/data-providers/GetBrickLibrary.ts
Labels: eve: release after merged

#457 fix(): style refine
  bricks/presentational-bricks/src/editor-bricks/index.ts
  bricks/shared-editors/src/editor-bricks/general-tag/general-tag.editor.module.css
Labels: eve: release after merged

#473 feat(snippet): add several snippets of page layout
  bricks/basic-bricks/snippets/easy-view.ts
  bricks/basic-bricks/snippets/thumbnails/easy-view.basic.svg
  bricks/basic-bricks/snippets/thumbnails/easy-view.right-aligned-menu.svg
Labels: eve: release after merged

#470 feat(basic-bricks): add brick header-bar
  .size-limit.js
  bricks/basic-bricks/src/header-bar/HeaderBar.spec.tsx
  bricks/basic-bricks/src/header-bar/HeaderBar.tsx
  bricks/basic-bricks/src/header-bar/index.headerBar.less
  bricks/basic-bricks/src/header-bar/index.spec.ts
  bricks/basic-bricks/src/header-bar/index.tsx
  bricks/basic-bricks/src/images/logo-139w.png
  bricks/basic-bricks/src/images/logo-278w.png
  bricks/basic-bricks/src/index.ts
  bricks/basic-bricks/stories/chapters/header-bar.ts
  bricks/basic-bricks/stories/chapters/index.ts
Labels: eve: release after merged

#484 feat(builder): use independent providers
  bricks/next-builder/src/builder-container/BuilderContainer.tsx
  bricks/next-builder/src/builder-container/BuilderUIContext.ts
  bricks/next-builder/src/builder-container/DataView/ContextItemForm.spec.tsx
  bricks/next-builder/src/builder-container/DataView/ContextItemForm.tsx
  bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.spec.tsx
  bricks/next-builder/src/builder-container/DataView/ContextItemFormModal.tsx
  bricks/next-builder/src/builder-container/DataView/DataView.spec.tsx
  bricks/next-builder/src/builder-container/DataView/DataView.tsx
  bricks/next-builder/src/builder-container/index.tsx
Labels: eve: release after merged
